<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-08T14:41:11 IST" name="Default suite" finished-at="2023-03-08T14:41:24 IST" duration-ms="13184">
    <groups>
    </groups>
    <test started-at="2023-03-08T14:41:11 IST" name="Default test" finished-at="2023-03-08T14:41:24 IST" duration-ms="13184">
      <class name="pk_Assignments.Assignment2">
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:pk_Assignments.Assignment2@16293aa2]" started-at="2023-03-08T14:41:11 IST" name="LaunchBrowser" finished-at="2023-03-08T14:41:19 IST" duration-ms="7425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method signature="login()[pri:0, instance:pk_Assignments.Assignment2@16293aa2]" started-at="2023-03-08T14:41:19 IST" name="login" description="Login into application" finished-at="2023-03-08T14:41:22 IST" duration-ms="3278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="navigateToSalesOrderPage()[pri:0, instance:pk_Assignments.Assignment2@16293aa2]" started-at="2023-03-08T14:41:22 IST" name="navigateToSalesOrderPage" description="Navigate to Sales Order Page" finished-at="2023-03-08T14:41:24 IST" depends-on-methods="pk_Assignments.Assignment2.login" duration-ms="2009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToSalesOrderPage -->
        <test-method signature="changeOrderStatus(java.lang.String,java.lang.String)[pri:0, instance:pk_Assignments.Assignment2@16293aa2]" started-at="2023-03-08T14:41:24 IST" name="changeOrderStatus" description="Change Order status to different values and verify colours" finished-at="2023-03-08T14:41:24 IST" depends-on-methods="pk_Assignments.Assignment2.navigateToSalesOrderPage" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void pk_Assignments.Assignment2.changeOrderStatus(java.lang.String,java.lang.String) requires a @DataProvider named : Different_Status_Scenario in class assignments.Test_Data]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void pk_Assignments.Assignment2.changeOrderStatus(java.lang.String,java.lang.String) requires a @DataProvider named : Different_Status_Scenario in class assignments.Test_Data
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeOrderStatus -->
        <test-method signature="resetOrderStatus()[pri:0, instance:pk_Assignments.Assignment2@16293aa2]" started-at="2023-03-08T14:41:24 IST" name="resetOrderStatus" description="Reset Order status back to Pending" finished-at="2023-03-08T14:41:24 IST" depends-on-methods="pk_Assignments.Assignment2.changeOrderStatus" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Assignment2.resetOrderStatus()[pri:0, instance:pk_Assignments.Assignment2@16293aa2] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Assignment2.resetOrderStatus()[pri:0, instance:pk_Assignments.Assignment2@16293aa2] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetOrderStatus -->
        <test-method signature="logout()[pri:0, instance:pk_Assignments.Assignment2@16293aa2]" started-at="2023-03-08T14:41:24 IST" name="logout" description="Logout from application" finished-at="2023-03-08T14:41:24 IST" depends-on-methods="pk_Assignments.Assignment2.resetOrderStatus" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Assignment2.logout()[pri:0, instance:pk_Assignments.Assignment2@16293aa2] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Assignment2.logout()[pri:0, instance:pk_Assignments.Assignment2@16293aa2] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:pk_Assignments.Assignment2@16293aa2]" started-at="2023-03-08T14:41:24 IST" name="CloseBrowser" finished-at="2023-03-08T14:41:24 IST" duration-ms="428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- pk_Assignments.Assignment2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
